# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: central # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}  # Sonatype JIRA 用户名
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}  # Sonatype JIRA 密码或 token
          GPG_SECRET_KEY: ${{ secrets.GPG_PRIVATE_KEY }}  # GPG 私钥（armored 格式）
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}  # GPG 密码短语
